config/routes.rb
Rails.application.routes.draw do
  resources :measures

  resources :probes

end

app/models/measure.rb
class Measure < ActiveRecord::Base
  belongs_to:probe
end

app/models/probe.rb
class Probe < ActiveRecord::Base
  has_many :measures
  attr_readonly :secret
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/measures_controller.rb
class MeasuresController < ApplicationController
  before_action :set_measure, only: [:show, :edit, :update, :destroy]
  
  # require any kind of change and creation of a measure to come through our authenticated api using HMAC 
  # and we skip the CSRF check for these requests
  before_action :require_authenticated_api, only: [:edit, :update, :destroy, :create]
  skip_before_action :verify_authenticity_token, only: [:edit, :update, :destroy, :create]

  def require_authenticated_api
    @current_probe = Probe.find_by_id(ApiAuth.access_id(request))
    
    # if a probe could not be found via the access id or the one found did not authenticate with the data in the request
    # fail the call
    if @current_probe.nil? || !ApiAuth.authentic?(request, @current_probe.secret) 
      flash[:error] = "Authentication required"
      redirect_to measures_url, :status => :unauthorized
    end
  end
        
  # GET /measures
  # GET /measures.json
  def index
    @measures = Measure.all
  end

  # GET /measures/1
  # GET /measures/1.json
  def show
  end

  # GET /measures/new
  def new
    @measure = Measure.new
  end

  # GET /measures/1/edit
  def edit
  end

  # POST /measures
  # POST /measures.json
  def create
    @measure = Measure.new(measure_params)

    respond_to do |format|
      if @measure.save
        format.html { redirect_to @measure, notice: 'Measure was successfully created.' }
        format.json { render :show, status: :created, location: @measure }
      else
        format.html { render :new }
        format.json { render json: @measure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measures/1
  # PATCH/PUT /measures/1.json
  def update
    respond_to do |format|
      if @measure.update(measure_params)
        format.html { redirect_to @measure, notice: 'Measure was successfully updated.' }
        format.json { render :show, status: :ok, location: @measure }
      else
        format.html { render :edit }
        format.json { render json: @measure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measures/1
  # DELETE /measures/1.json
  def destroy
    @measure.destroy
    respond_to do |format|
      format.html { redirect_to measures_url, notice: 'Measure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measure
      @measure = Measure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measure_params
      params.require(:measure).permit(:temperature)
    end
end

app/controllers/probes_controller.rb
class ProbesController < ApplicationController
  before_action :set_probe, only: [:show, :edit, :update, :destroy]

  # GET /probes
  # GET /probes.json
  def index
    @probes = Probe.all
  end

  # GET /probes/1
  # GET /probes/1.json
  def show
  end

  # GET /probes/new
  def new
    @probe = Probe.new
  end

  # GET /probes/1/edit
  def edit
  end

  # POST /probes
  # POST /probes.json
  def create
    @probe = Probe.new(probe_params)
    
    @probe.secret = ApiAuth.generate_secret_key

    respond_to do |format|
      if @probe.save
        format.html { redirect_to @probe, notice: 'Probe was successfully created.' }
        format.json { render :show, status: :created, location: @probe }
      else
        format.html { render :new }
        format.json { render json: @probe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /probes/1
  # PATCH/PUT /probes/1.json
  def update
    respond_to do |format|
      if @probe.update(probe_params)
        format.html { redirect_to @probe, notice: 'Probe was successfully updated.' }
        format.json { render :show, status: :ok, location: @probe }
      else
        format.html { render :edit }
        format.json { render json: @probe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /probes/1
  # DELETE /probes/1.json
  def destroy
    @probe.destroy
    respond_to do |format|
      format.html { redirect_to probes_url, notice: 'Probe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_probe
      @probe = Probe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def probe_params
      params.require(:probe).permit(:name, :secret)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/measures_helper.rb
module MeasuresHelper
end

app/helpers/probes_helper.rb
module ProbesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArduinoAuthenticatedClientExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% flash.each do |name, msg| -%>
		<%= content_tag :div, msg, class: name %>
	<% end -%>
<%= yield %>

</body>
</html>

app/views/measures/_form.html.erb
<%= form_for(@measure) do |f| %>
  <% if @measure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@measure.errors.count, "error") %> prohibited this measure from being saved:</h2>

      <ul>
      <% @measure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :temperature %><br>
    <%= f.text_field :temperature %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/measures/edit.html.erb
<h1>Editing measure</h1>

<%= render 'form' %>

<%= link_to 'Show', @measure %> |
<%= link_to 'Back', measures_path %>

app/views/measures/index.html.erb
<h1>Listing measures</h1>

<table>
  <thead>
    <tr>
      <th>Temperature</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @measures.each do |measure| %>
      <tr>
        <td><%= measure.temperature %></td>
        <td><%= link_to 'Show', measure %></td>
        <td><%= link_to 'Edit', edit_measure_path(measure) %></td>
        <td><%= link_to 'Destroy', measure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Measure', new_measure_path %>

app/views/measures/new.html.erb
<h1>New measure</h1>

<%= render 'form' %>

<%= link_to 'Back', measures_path %>

app/views/measures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Temperature:</strong>
  <%= @measure.temperature %>
</p>

<%= link_to 'Edit', edit_measure_path(@measure) %> |
<%= link_to 'Back', measures_path %>

app/views/probes/_form.html.erb
<%= form_for(@probe) do |f| %>
  <% if @probe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@probe.errors.count, "error") %> prohibited this probe from being saved:</h2>

      <ul>
      <% @probe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :secret %><br>
    <%= f.text_field :secret %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/probes/edit.html.erb
<h1>Editing probe</h1>

<%= render 'form' %>

<%= link_to 'Show', @probe %> |
<%= link_to 'Back', probes_path %>

app/views/probes/index.html.erb
<h1>Listing probes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Secret</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @probes.each do |probe| %>
      <tr>
        <td><%= probe.name %></td>
        <td><%= probe.secret %></td>
        <td><%= link_to 'Show', probe %></td>
        <td><%= link_to 'Edit', edit_probe_path(probe) %></td>
        <td><%= link_to 'Destroy', probe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Probe', new_probe_path %>

app/views/probes/new.html.erb
<h1>New probe</h1>

<%= render 'form' %>

<%= link_to 'Back', probes_path %>

app/views/probes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @probe.name %>
</p>

<p>
  <strong>Secret:</strong>
  <%= @probe.secret %>
</p>

<%= link_to 'Edit', edit_probe_path(@probe) %> |
<%= link_to 'Back', probes_path %>